### ISSUE TITLE
Gimme free picture pasting, GitHub!

### ISSUE THREAD

**Issue by OnkelTem** [OnkelTem/audio_silence_marks#1]
Voilà:

![image](https://user-images.githubusercontent.com/114060/99714622-dc196b80-2ab6-11eb-977d-cd3d58ff1786.png)
![image](https://user-images.githubusercontent.com/114060/99715000-5cd86780-2ab7-11eb-8707-b7235bebebf3.png)

**Comment by KOLANICH** [comment]
You don't have to keep this issue (repo owner can delete issues) in order to keep the links to pics alive. In fact it works even if an issue is not created at all.

**Comment by OnkelTem** [comment]
> You don't have to keep this issue (repo owner can delete issues) in order to keep the links to pics alive.

Really? Ha-ha.
>  In fact it works even if an issue is not created at all.

No saved you mean? So they don't calculate usages of the pictures.

 Thank you, good to know.

**Comment by KOLANICH** [comment]
>So they don't calculate usages

IDK if they do, but the links to images created this way (opening an new issue page, uploading a file, taking the link, closing the page without actually creating an issue, using the link somewhere else) are working for more than 3 years. Works with existing issue comments too.

>of the pictures.

not only pictures.

And under deleting an issue I meant deleting, not closing, making it completely disappear.

**Comment by OnkelTem** [comment]
Thank you, sir! :)

**Comment by KOLANICH** [comment]
>sir

I have never been knighted and I am not going to. It is completely inacceptable to become a part of souvereign-vassal hierarchy.
